//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyC.CGRyF.AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CNA_SIRFIC_Entities : DbContext
    {
        public CNA_SIRFIC_Entities()
            : base("name=CNA_SIRFIC_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblACAsistencia> tblACAsistencias { get; set; }
        public virtual DbSet<tblLocalidadINEGI> tblLocalidadINEGIs { get; set; }
        public virtual DbSet<tblPuucContadorPublico> tblPuucContadorPublicoes { get; set; }
        public virtual DbSet<tblPuucContribuyente> tblPuucContribuyentes { get; set; }
        public virtual DbSet<tblPuucDomicilioContribuyente> tblPuucDomicilioContribuyentes { get; set; }
        public virtual DbSet<tblPuucRelContribuyenteCorreo> tblPuucRelContribuyenteCorreos { get; set; }
        public virtual DbSet<tblPuucRelContribuyenteTelefono> tblPuucRelContribuyenteTelefonos { get; set; }
        public virtual DbSet<tblPuucRelDomicilioContribuyente> tblPuucRelDomicilioContribuyentes { get; set; }
        public virtual DbSet<tblPuucRepresentanteLegal> tblPuucRepresentanteLegals { get; set; }
        public virtual DbSet<tblSubRama> tblSubRamas { get; set; }
    }
}
