//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyC.CGRyF.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblACAsistencia
    {
        public long id { get; set; }
        public Nullable<int> tipoAsistencia { get; set; }
        public Nullable<long> idContribuyente { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string tiempoAtencion { get; set; }
    
        public virtual tblPuucContribuyente tblPuucContribuyente { get; set; }
    }
}
