//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyC.CGRyF.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPuucRelContribuyenteTelefono
    {
        public long id { get; set; }
        public long idContribuyente { get; set; }
        public string numeroTelefonico { get; set; }
        public string lada { get; set; }
        public string extension { get; set; }
        public Nullable<int> tipo { get; set; }
    
        public virtual tblPuucContribuyente tblPuucContribuyente { get; set; }
    }
}
